eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@172.16.158.66:13000/eureka/,http://admin:123456@172.16.158.67:12000/eureka/,http://admin:123456@172.16.158.68:14000/eureka/
    register-with-eureka: true
    fetch-registry: true



spring:
  redis:
    database: 11
    # 地址
    host: r-bp17397fc4574364.redis.rds.aliyuncs.com    #同催收系统
    # 端口，默认为6379
    port: 6379
    # 密码
    password: LvXlmVeeGNvaAli7
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      first:  #数据源1
        url: jdbc:mysql://rm-bp184g9c4es872a34.mysql.rds.aliyuncs.com:3306/lz_express?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: lt_biz
        password: jmJfB36ret46
      second:  #数据源2
        url: jdbc:mysql://rm-bp178z79t7d8egd47.mysql.rds.aliyuncs.com:3306/lz_express?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: collection_biz
        password: i4tB@q^7yM0pn8d&2
      initial-size: 10
      max-active: 10
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true




