eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@172.16.158.55:1100/eureka/
    register-with-eureka: true
    fetch-registry: true



spring:
  redis:
    host: 172.16.157.238
    password: Hello1234
    port: 6379
    database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      first:  #数据源1
        url: jdbc:mysql://172.16.157.238:3306/lz_express?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: ldd_biz
        password: Hello1234
      second:  #数据源2
        url: jdbc:mysql://172.16.157.238:3306/lz_express?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: ldd_biz
        password: Hello1234
      initial-size: 10
      max-active: 10
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

